version: '3.8'

services:
  libretranslate:
    build:
      context: .
      dockerfile: docker/Dockerfile.interlnkd
    image: interlnkd_libretranslate
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/app
      - libretranslate_models:/home/libretranslate/.local/share/argos-translate
    ports:
      - 5001:5001
    env_file:
      - .env.prod
    environment:
      - FLASK_APP=app
      - LT_LOAD_ONLY=${LT_LOAD_ONLY}
      - LT_UPDATE_MODELS=false
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6380"

  celery_worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.interlnkd
    image: celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
      - libretranslate_models:/home/libretranslate/.local/share/argos-translate
    env_file:
      - .env.prod
    environment:
      - FLASK_APP=app
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: docker/Dockerfile.interlnkd
    image: celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
      - libretranslate_models:/home/libretranslate/.local/share/argos-translate
    env_file:
      - .env.prod
    environment:
      - FLASK_APP=app
    depends_on:
      - redis

  flower:
    build:
      context: .
      dockerfile: docker/Dockerfile.interlnkd
    image: celery_flower
    command: /start-flower
    volumes:
      - .:/app
      - libretranslate_models:/home/libretranslate/.local/share/argos-translate
    env_file:
      - .env.prod
    environment:
      - FLASK_APP=app
    ports:
      - 5557:5555
    depends_on:
      - redis

volumes:
  libretranslate_models: