#!/bin/bash

# Exit immediately if a command exits with a non-zero status.
set -o errexit
# Exit if any command in a pipeline fails.
set -o pipefail
# Exit if trying to use an undefined variable.
set -o nounset

# Start the passed command (e.g., /start or gunicorn)
exec "$@"
